### ISSUE TITLE
Slather Breaks Bitcode

### ISSUE THREAD

**Issue by calebd** [SlatherOrg/slather#115] opened 2015-11-30 18:41 UTC
Just thought I would post this here and see if there is a good solution. The build settings required by Slather break Bitcode. Related: https://github.com/soffes/RateLimit/issues/18.

**Comment by calebd** [comment] 2015-11-30 18:42
I suppose you could recommend that people only enable the two required build settings in a debug configuration which the test phase of a scheme targets by default.

**Comment by neonichu** [comment] 2016-02-03 23:13
This is basically a duplicate of #73

**Closed by neonichu** 2016-02-03 23:13 UTC
