### ISSUE TITLE
Unable to get coverage data from XCode UI Test schemes

### ISSUE THREAD

**Issue by K76154** [SlatherOrg/slather#163] opened 2016-03-05 14:06 UTC
I ran slather against XCode UI Test schemes, and it told me "No product binary found". I then set --binary-file to either the target app's product binary or the UI Test's xctest binary. Both ended up giving me a cobertura.xml with 0% coverage. It appears that the code now is bound to Unit Test only and can't process UI Tests.

**Comment by ksuther** [comment] 2016-03-29 21:57
You might try this with Xcode 7.3 and the latest master version of slather. Xcode 7.2 didn't write coverage for UI Tests, at least for Mac projects.

**Comment by neonichu** [comment] 2016-04-06 13:49
Duplicate of #151

**Closed by neonichu** 2016-04-06 13:49 UTC

**Comment by gelemias** [comment] 2016-04-13 10:08
Hi, when i run the tests in command line setting my own path for derived data I don't get coverage for UI Automated tests using latest Xcode and sdk.

Am I missing something? it works when running tests in Xcode and running slather afterwards without setting build_directory,

**Comment by ksuther** [comment] 2016-04-13 14:31
What are your slather arguments? Are you specifying your derived data directory?

**Comment by gelemias** [comment] 2016-04-14 07:42
in my .slather.yml I have set `output_directory`, should I specify derived data path differently? 

this is how I trigger tests and slather afterwards.

```
set -o pipefail; xcodebuild -workspace "$(APP_WORKSPACE_NAME)" -verbose -scheme "$(APP_TEST_SCHEME_NAME)" -destination "$(APP_TEST_TARGET)" -configuration Debug -derivedDataPath "$(APP_TEST_OUTPUT_PATH)" test | xcpretty -c -t -r junit

slather coverage --teamcity -s
```

.slather.yml
```
workspace: app.xcworkspace
xcodeproj: app.xcodeproj
scheme: app
source_directory: app
output_directory: build/reports/coverage
build_directory: build/Test
ignore:
```

**Comment by ksuther** [comment] 2016-04-14 17:56
`build_directory` should be the same as your derivedDataPath. If you run slather with `--verbose` you can also see the paths it is checking.

**Comment by gelemias** [comment] 2016-04-15 06:26
Thank you! 

It seems to be an issue with running tests through the command line because the Coverage.profdata generated using xcodebuild is different than the one that Xcode generates.

**Comment by thelvis4** [comment] 2016-07-12 11:48
@gelemias you are right! See https://github.com/nakiostudio/xcov/issues/22#issuecomment-232014641
