### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by Tiny0529** [SlatherOrg/slather#431] opened 2019-08-09 06:42 UTC
slather coverage -x --verbose --output-directory sonar-reports/cobertura.xml --source-files Classes/xx.m --scheme iLife --workspace xx.xcworkspace xx.xcodeproj
Slathering...

Processing coverage file: /Users/xx/Library/Developer/Xcode/DerivedData/xx-bjvnokbuenhgoifyeirbwfwusokf/Build/ProfileData/4FFDFBE8-97B6-4AB0-9AF2-FF1078D2B40B/Coverage.profdata
Against binary files:
	/Users/xx/Library/Developer/Xcode/DerivedData/xx-bjvnokbuenhgoifyeirbwfwusokf/Build/Products/Debug-iphonesimulator/xx.app/xx

sh: /usr/bin/xcrun: Argument list too long

**Comment by weibel** [comment] 2020-01-28 07:57
This issue and issues https://github.com/SlatherOrg/slather/issues/442 and possibly https://github.com/SlatherOrg/slather/issues/441 seems a lot like issue https://github.com/SlatherOrg/slather/issues/243 which PR https://github.com/SlatherOrg/slather/pull/414 fixed long time ago. I suspect there's a change in MacOS Catalina which throws an error different from Errno::E2BIG. It might also be a completely different problem, but it's difficult to say without more info.

**Comment by kapfab** [comment] 2020-04-01 18:27
We're encountering the same issue since about two months on one of our projects, for some builds only (but reproducible with these builds).

PR #414 actually catches the `E2BIG` error in most cases (I’ve seen it split the command line in two for other projects/branches), but in these specific cases, the error is not caught.
But we still end up with the same `/usr/bin/xcrun: Argument list too long` message.
So I also suspect another error than E2BIG to be thrown.

Note that in these cases, the total length of `"xcrun llvm-cov"` + `source_files` + `llvm_cov_args` is less than ARG_MAX (262144 bytes for Catalina), even if I add the 1802 bytes of env vars (I read they could count in `ARG_MAX`).
And AFAIK, we have no filenames with non-latin characters that could use more than 1 byte.

**Comment by yfujiki** [comment] 2021-02-09 21:41
And nope. Above doesn't fix it.

**Comment by ksuther** [comment] 2021-02-20 00:14
Fixed by #476.

**Closed by ksuther** 2021-02-20 00:14 UTC
