### ISSUE TITLE
Support for multiple output 

### ISSUE THREAD

**Issue by soheilbm** [SlatherOrg/slather#102] opened 2015-09-25 07:44 UTC
It would be great if I could export multiple output with 1 line of command. 

```
slather coverage -x --html --output-directory MyTests
```

**Comment by neonichu** [comment] 2016-02-03 22:43
Duplicate of #133 (it's newer, but I was going through issues top to bottom, sorry)

**Closed by neonichu** 2016-02-03 22:43 UTC
