### ISSUE TITLE
unable to find a version of 'activesupport' to activate

### ISSUE THREAD

**Issue by trongcuong1710** [SlatherOrg/slather#254] opened 2016-10-12 16:26 UTC
I'm trying slather in conjunction with fastlane to generate code coverage for my iOS project. When trying to run slather, I faced with "unable to find a version of 'activesupport' to activate".

```
/Users/DFS/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'activesupport' to activate (Gem::LoadError)
    from /Users/DFS/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object_attributes.rb:15:in `<class:AbstractObjectAttribute>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object_attributes.rb:14:in `<module:Object>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object_attributes.rb:3:in `<class:Project>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object_attributes.rb:2:in `<module:Xcodeproj>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object_attributes.rb:1:in `<top (required)>'
    from /Users/DFS/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/DFS/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/DFS/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object.rb:481:in `<top (required)>'
    from /Users/DFS/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/DFS/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/DFS/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project.rb:4:in `<top (required)>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/gems/slather-2.3.0/lib/slather/project.rb:9:in `<module:Xcodeproj>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/gems/slather-2.3.0/lib/slather/project.rb:7:in `<top (required)>'
    from /Users/DFS/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/DFS/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/gems/slather-2.3.0/lib/slather.rb:2:in `<top (required)>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/gems/slather-2.3.0/bin/slather:4:in `require_relative'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/gems/slather-2.3.0/bin/slather:4:in `<top (required)>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/bin/slather:22:in `load'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/bin/slather:22:in `<main>'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/DFS/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

Here is my gem list:

```
actionmailer (4.2.4)
actionpack (4.2.4, 4.2.2, 4.2.0)
actionview (4.2.4, 4.2.2, 4.2.0)
activejob (4.2.4)
activemodel (4.2.4, 4.2.2, 4.2.0)
activerecord (4.2.4)
activesupport (4.2.7.1, 4.2.4, 4.2.2, 4.2.0)
....
```

**Comment by Sloox** [comment] 2016-10-31 14:08
I have exactly the same issue.
Running a local build (on my machine) executes perfectly,
However running this on Jenkins results in the above issue.
Any update or ideas would be greatly appreciated.

**Comment by alan-honeycutt** [comment] 2016-11-03 15:25
It's most likely a Ruby version thing. Update to the latest (2.3.1), install/update your gems, and try again.

**Comment by Sloox** [comment] 2016-11-04 10:09
Updating ruby & reconfiguring fixed it for me.

**Comment by trongcuong1710** [comment] 2017-01-16 10:17
I switched to use xcov for test coverage. Will try out with latest ruby and update here later.

**Comment by ksuther** [comment] 2017-03-29 21:25
Closing as a duplicate of #239.

**Closed by ksuther** 2017-03-29 21:25 UTC
