### ISSUE TITLE
Not finding coverage files with Xcode 7

### ISSUE THREAD

**Issue by tspecht** [SlatherOrg/slather#154] opened 2016-02-24 18:34 UTC
Hi guys,

I'm trying to run slather to generate a coverage report of my app tested with Xcode 7. I triple checked that I have "Generate Code Coverage" enabled in my scheme.

Here's the error I'm receiving:

```
[!] Exit status of command 'slather coverage --scheme MyProjectTests MyProject.xcodeproj' was 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
Slathering...
/Users/myUser/.rvm/gems/ruby-2.2.0/gems/slather-2.0.1/lib/slather/project.rb:290:in `find_binary_file': No product binary found in /Users/myUser/Library/Developer/Xcode/DerivedData/MyProject-feagzyrzafumrqfimizbpaeyingz/Build/Intermediates/CodeCoverage/MyProjectTests. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj`
```

The weird part is, when I open that directory, I clearly can see the coverage files (.hmap) being there?

![screen shot 2016-02-24 at 19 32 19](https://cloud.githubusercontent.com/assets/603144/13296379/9df1bf8e-db2d-11e5-8fbd-feff0c13f684.png)

Any hints?

**Comment by neonichu** [comment] 2016-02-25 09:50
Nope `.hmap` files are not coverage data, the files Xcode 7 uses have the extension `.profdata`.

**Comment by tspecht** [comment] 2016-02-25 09:52
Hm okay. Any idea what could go wrong then?

**Comment by palusik86** [comment] 2016-02-26 11:50
Same here, any ideas ?

**Comment by elitalon** [comment] 2016-02-26 15:18
I also had this issue and deleting the `DerivedData` directory solved the issue. I don't know what I had there that could affect the inner workings of slather.

**Comment by palusik86** [comment] 2016-02-26 15:21
Still can't do that. Clean Derived Data not solved this. I use local and remote Slather (Jenkins).

**Comment by ryang1428** [comment] 2016-02-29 15:37
I am seeing the same issue. I am trying to setup slather for the first time on our Jenkins server.

**Comment by palusik86** [comment] 2016-03-01 09:25
Still struggling with this, now on more projects. Always the same...

**Comment by ynnadkrap** [comment] 2016-03-01 20:35
I'm having the same issue local and remote (travis-ci). Tried deleting deriveddata.

**Comment by Sarkazein** [comment] 2016-03-02 18:52
I can confirm that we're seeing the same issue/fix as @palusik86 .  Will be testing a few other projects to see if it's a local config issue or what, since I'd expect to see many more issues being raised for this if it was a general Xcode 7 issue.

**Comment by ryang1428** [comment] 2016-03-03 16:52
Not sure whats going on with this. I re-tried today and my slather reports were generated locally, but I still get this error on our Jenkins server.

**Comment by palusik86** [comment] 2016-03-03 17:19
1.8.3 does not have this error, in 2.0.x there was many changes. Before update on Jenkins it was working. Check your version Jenkins.

**Comment by heitortsergent** [comment] 2016-03-17 21:04
Same error here, tested with Xcode 7.2.1, and Slather 2.0.0, and 2.0.1. Making the change that @palusik86 mentioned on the `project.rb` file fixes it.

**Comment by neonichu** [comment] 2016-04-06 13:49
Should be fixed by https://github.com/SlatherOrg/slather/releases/tag/v2.1.0 — please let us know if it is not.

**Closed by neonichu** 2016-04-06 13:49 UTC

**Comment by chriswunsch00** [comment] 2017-06-23 13:39
I had this issue with Jenkins but resolved it by using 'Debug' for the configuration of the XCodeBuild rather than 'Release'
